### ISSUE TITLE
As an admin, I can login and then change the content on the Habitat page using the Admin dashboard

### ISSUE THREAD

**Issue by kathleenahall** [WebJamApps/CollegeLutheran#516]
- [ ] Admin Dashboard updates
- [ ] Habitat page updates
- [ ] Content provider updates
